services:
  - type: web
    name: witchina-ink-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: BOT_TOKEN
        value: 8833234277:AAFil5ZSPVYqoZhkS6OniM1EpaxHdBbmLRA
      - key: ADMIN_ID
        value: 623268834
      - key: PORT
        value: 10000